language: ruby
sudo: false
cache: bundler
script: bundle exec rake generate
after_success:
- git config --global user.email "openenergymonitor@users.noreply.github.com"
- git config --global user.name "Glyn Hudson"
- '[ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && bundle exec rake deploy || false'
env:
  global:
  - secure: F98OsMVePgfVSaWfG9NI9Pr4agb3lkXq0HNgSx/Mx8rkrtobDxphP024Q2ef636f2k0hueheSZ8jjC3H1aX7IhKDg4Ef19P0Ozw7Ccz89GHWkV/5DgwkOY/Syxc+CwFpsD5VxDV8GGB04N2FD/6HwY8twEjBY6s0WPR7TS/ZZEXRoPNHtGzcFSFnJKkX3w+ITgRvbWyJAjmywWkOdCuxhoOHSO86U/UDj8VeiAHWU/LDawYOOOdV1TX2Zpslh3Lc4Ohj95v8sD+X7eXXKQXbYJGuvM26xgJZclOi/Uw7eVmV6ONDkAgxAc0vSDzqE2fwyZkZ3PHHJoVi8tOo2XARTrfsLW26gc4n07V4Fu9UUcxx6vZUmGrEG9jFYO0vHJ8m4DHYXJKPogn/sGBqWEasgIeQ4WRM7qs35YMQhDZaMMHJqxJRV2ZjW10rAeEmiakB/DR4hsEAnZFLupfeamWZ9gJpNZJZRdHcMlSXeTx7wuqWVFDlW8IF9jKt2Ce8JczKvM1YvHxLZwy2YNRPjfx0yzPQKQIE3a2s/3n5r99NP6XDtg5+v+t85ljc57Vvn+3+S0Jhz+TejATflq8m7qplkiz4JSmWMH6RwrEoz4EsFYP3wVOq82blSR/wczPal3SOKxjFuljmtG+m8xiCVGq/liToIKXioOgVFIaStZaXNDY=
